<h1>Импорт библиотек

In [1]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [15]:

import numpy as np

def sum_prod(X, V):

    #X - список из p матриц размерностью (n, n)
    #V - список из p векторов размерностью (n, 1)
    #Возвращает сумму произведений каждой матрицы на соответствующий вектор.

    # Проверка, что количество матриц и векторов одинаковое
    assert len(X) == len(V) #Количество матриц должно совпадать с количеством векторов

    result = np.zeros((len(V[0]), 1)) # Инициализируем результирующий вектор
    for i in range(len(X)):
        result += np.dot(X[i], V[i]) # Умножение матрицы на вектор и суммирование
    return result

# Пример тестов
def test_sum_prod():
# Тест 1: проверка на небольших данных
    X = [np.array([[1, 2], [3, 4]]), np.array([[2, 0], [0, 2]])]
    V = [np.array([[1], [1]]), np.array([[2], [2]])]
    result = sum_prod(X, V)
    expected = np.array([[9], [15]]) # Ожидаемый результат
    assert np.allclose(result, expected), f"Ошибка в тесте 1: {result} != {expected}"

    # Тест 2: проверка на случай, когда все матрицы и векторы – нулевые
    X = [np.zeros((2, 2)), np.zeros((2, 2))]
    V = [np.zeros((2, 1)), np.zeros((2, 1))]
    result = sum_prod(X, V)
    expected = np.zeros((2, 1))
    assert np.allclose(result, expected), f"Ошибка в тесте 2: {result} != {expected}"

    # Тест 3: проверка на единичных матрицах и векторах
    X = [np.eye(2), np.eye(2)]
    V = [np.ones((2, 1)), np.ones((2, 1))]
    result = sum_prod(X, V)
    expected = np.array([[2], [2]])
    assert np.allclose(result, expected), f"Ошибка в тесте 3: {result} != {expected}"

print("Все тесты пройдены!")

# Запуск тестов
test_sum_prod()



Все тесты пройдены!


AssertionError: Ошибка в тесте 1: [[ 7.]
 [11.]] != [[ 9]
 [15]]

<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [10]:
import numpy as np

def binarize(M, threshold=0.5):

#Бинаризация матрицы M по порогу threshold.
#Значения, большие порога, становятся 1, остальные 0.

    return (M > threshold).astype(int)

# Пример тестов
def test_binarize():
    # Тест 1: стандартный случай с порогом 0.5
    M = np.array([[0.2, 0.6], [0.7, 0.3]])
    result = binarize(M)
    expected = np.array([[0, 1], [1, 0]])
    assert np.array_equal(result, expected), f"Ошибка в тесте 1: {result} != {expected}"

    # Тест 2: порог 0.7
    M = np.array([[0.2, 0.8], [0.7, 0.9]])
    result = binarize(M, threshold=0.7)
    expected = np.array([[0, 1], [0, 1]])
    assert np.array_equal(result, expected), f"Ошибка в тесте 2: {result} != {expected}"

    # Тест 3: порог 1 (все значения должны быть 0)
    M = np.array([[0.2, 0.8], [0.7, 0.9]])
    result = binarize(M, threshold=1)
    expected = np.array([[0, 0], [0, 0]])
    assert np.array_equal(result, expected), f"Ошибка в тесте 3: {result} != {expected}"

    # Тест 4: порог 0 (все значения должны быть 1)
    M = np.array([[0.2, 0.8], [0.7, 0.9]])
    result = binarize(M, threshold=0)
    expected = np.array([[1, 1], [1, 1]])
    assert np.array_equal(result, expected), f"Ошибка в тесте 4: {result} != {expected}" 
    print("Все тесты пройдены!")

# Запуск тестов
test_binarize()


Все тесты пройдены!


<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [13]:
import numpy as np

def unique_rows(mat):
    
    #Возвращает уникальные элементы для каждой строки матрицы.
    
    return [np.unique(row) for row in mat]

def unique_columns(mat):

    #Возвращает уникальные элементы для каждого столбца матрицы.
    
    return [np.unique(col) for col in mat.T]  # Транспонируем матрицу для работы со столбцами

# Пример тестов
def test_unique_rows_and_columns():
    mat = np.array([[1, 2, 2, 3],
                    [3, 3, 3, 4],
                    [5, 5, 6, 6]])
    
    # Тест для уникальных элементов строк
    result_rows = unique_rows(mat)
    expected_rows = [np.array([1, 2, 3]), np.array([3, 4]), np.array([5, 6])]
    assert all(np.array_equal(result, expected) for result, expected in zip(result_rows, expected_rows)), f"Ошибка в unique_rows: {result_rows} != {expected_rows}"
    
    # Тест для уникальных элементов столбцов
    result_columns = unique_columns(mat)
    expected_columns = [np.array([1, 3, 5]), np.array([2, 3, 5]), np.array([2, 3, 6]), np.array([3, 4, 6])]
    assert all(np.array_equal(result, expected) for result, expected in zip(result_columns, expected_columns)), f"Ошибка в unique_columns: {result_columns} != {expected_columns}"
    
    print("Все тесты пройдены!")

# Запуск тестов
test_unique_rows_and_columns()


Все тесты пройдены!


<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [ ]:
# Your code goes here

<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [ ]:
def chess(m, n, a, b):
    # Your code goes here
    pass

<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [1]:
def draw_rectangle(a, b, m, n, rectangle_color, background_color):
    # Your code goes here
    pass

def draw_ellipse(a, b, m, n, ellipse_color, background_color):
    # Your code goes here
    pass

<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [ ]:
# Your code goes here

<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [14]:
import numpy as np

def one_hot_encode(vector):
    # Определяем количество уникальных классов
    num_classes = np.max(vector) + 1
    # Выполняем one-hot encoding
    one_hot = np.eye(num_classes)[vector]
    return one_hot

# Пример использования
vector = [0, 2, 3, 0]
encoded = one_hot_encode(vector)
print(encoded)


[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
